### ISSUE TITLE
Plugin conflict: LogicException thrown by another plugin during init()

### ISSUE THREAD

**Issue by johndwells** [fruitstudios/craft-searchit#10]
I have the Feed Me plugin installed alongside SearchIt, and when I visit the CP I periodically get this `LogicException` thrown:

> Unable to register extension "verbb\feedme\web\twig\Extension" as extensions have already been initialized.

At first I thought it was a bug in Feed Me (https://github.com/verbb/feed-me/issues/468) but after digging I found that it's more likely caused by SearchIt calling `$view = Craft::$app->getView();` as part of it's `init()` routine.

### More Info:
Craft Version: 3.0.40
SearchIt Version: 1.0.3
Feed Me Version: 3.0.2.1

**Comment by jcrichto** [comment]
I'm seeing a very similar issue with another plugin imager.  I get this error:

`Unable to register extension "aelvan\imager\twigextensions\ImagerTwigExtension" as extensions have already been initialized.`

The minute I disable the searchit plugin, the problem seems goes away. Has this problem been resolved with the similar issue above?

**More Info:**
Craft CMS 3.1.19
Searchit 1.0.6
Imager v2.1.7

**Comment by samhibberd** [comment]
Fixed in 1.0.7. Thanks @johndwells
